#!/bin/bash

# Q&D script to tweet voter info to a random sequence of all the states, separated
# by random intervals, but no less than 10 minutes.  The cycle fits into ~24hrs.
# Meant to run in the background over the course of a day.

# Suppress some actions when debugging (-x)
exec=
[[ "$-" =~ .*x.* ]] && exec=:

usage() {
	echo "Usage:
$0 -h
$0 [-q number-of-tweets(min 4)] [-w time-period(max 86400 sec)] [-b base-interval(default 600)] { [-S tweep_file] | [-s state] } campaign"
}
exclu_msg="-s and -S are mutually exclusive."

set_boundaries() {
	# Set fail-safe bounds on input params that determine tweet period and intervals.
	# Calibration: minimum 10 min. interval.  Set of len(step_seq) intervals adds to "Elapsed:"
	# hours, so all states will be tweeted within "waking hours" (approx. 16 hrs., e.g. 6AM-10PM).
	# This algorithm applies for states as well as cities within a state.
	[ "$Quanta" -ge 4 -a "$Quanta" -le ${#step_seq[@]} ] 2>- || Quanta=${#step_seq[@]}
	[ "$Waking_hrs" -ge 0 -a "$Waking_hrs" -le 86400 ] 2>- || Waking_hrs=$((16 * 60 * 60))  # sec.
}

build_voterinfo_seq() {
	local step_gen

	# Be careful to quote multi-word names into the array
	if [ -z "$State" ]; then
		step_gen="
import campaign
import render
render.all_states(campaign.campaigns['"$Campaign"'])
"
	else
		step_gen="
import campaign
import render
render.all_cities(campaign.campaigns['"$Campaign"'], '"$State"')
"
	fi
	eval step_seq=( `python -c "$step_gen" | shuf` )
}

build_tweep_seq() {
	step_seq=( `awk 'BEGIN { FS="|" } { print $2 }' $Tweep_file` )
}

build_interval_seq() {
	# Generate a shuffled list of wait intervals spread over a time period.
	# We have one Base_wait interval, then ($Quanta - 2) wait intervals occurring between steps.
	local delta time_period

	time_period=$1
	delta=`exec 2>-; echo $(( ($time_period - (($Quanta - 2) * $Base_wait)) / (($Quanta - 2)**2 / 2) ))`
	[ "$delta" -ge 0 ] 2>- || delta=0
	echo "quanta: $Quanta, delta: $delta"
	interval_seq=( `count=1; time=$Base_wait;
			while [ $count -lt $Quanta ]; do
				echo $time; time=$(($time + $delta)); count=$(($count + 1));
			done | shuf` )
	interval_seq=( ${interval_seq[@]} 0 )	# Terminate interval list
	echo "Elapsed:" $(((`echo ${interval_seq[*]} | sed 's/ /+/g'`) / 60)) "min."
}

print_tweet_schedule() {
	local i

	i=0
	echo -n "Steps/intervals: "
	while [ -n "${step_seq[$i]}" -a -n "${interval_seq[$i]}" ]; do
		if [ -z "$State" ]; then
			echo -n "${step_seq[$i]}/${interval_seq[$i]}"
		else
			echo -n "$(($i + 1))/${interval_seq[$i]}"
		fi
		echo -n " "
		i=$(($i + 1))
	done
}

tweet_loop() {
	# Enter a tweet loop, calling the action function at each interval
	local i action

	action=$1
	i=0
	while [ -n "${step_seq[$i]}" -a -n "${interval_seq[$i]}" ]; do
		echo
		if [ -z "$State" ]; then
			echo "Step $(($i + 1)): ${step_seq[$i]}, interval ${interval_seq[$i]}"
		else
			echo "Step $(($i + 1)), interval ${interval_seq[$i]}"
		fi

		eval $action $i
		$exec sleep ${interval_seq[$i]}
		i=$(($i + 1))
	done
}

voterinfo_tweet() {
	local place

	# For cities in a state, always tweet the same state
	[ -z "$State" ] && place="${step_seq[$1]}" || place="$State"
	$exec python voterinfo.py $Campaign "$place"
}

socialize_tweet() {
	$exec python socialize.py $Campaign "${step_seq[$1]}"
}

#
# ------------ Main logic ------------
#

Action_fn=voterinfo_tweet
Build_step_seq=build_voterinfo_seq
Base_wait=600
while getopts hs:q:w:S:b: option; do
	case $option in
	h) usage
		exit 0
		;;
	s)
		[ -n "$Tweep_file" ] && { echo "$exclu_msg"; usage; exit 1; }
		State="$OPTARG"
		;;
	q) Quanta="$OPTARG"
		;;
	w) Waking_hrs="$OPTARG"
		;;
	S)
		[ -n "$State" ] && { echo "$exclu_msg"; usage; exit 1; }
		Tweep_file="$OPTARG"
		Action_fn=socialize_tweet
		Build_step_seq=build_tweep_seq
		;;
	b) Base_wait="$OPTARG"
		;;
	?) usage
		exit 1
	esac
done

args=("$@")
OPTIND=$(($OPTIND - 1))
Campaign="${args[$OPTIND]}"
[ -n "$Campaign" ] || { usage; exit 1; }

eval $Build_step_seq

set_boundaries

build_interval_seq $Waking_hrs

print_tweet_schedule

# Enter tweeting loop.
# NOTE: For this algorithm, a "step" will contain a city name if the script was invoked with -s,
# or a Twitter username if invoked with -S.
tweet_loop $Action_fn
